import React from 'react';
import styles from '@/styles/authpage.module.scss';

export const metadata = {
  title: 'Signup/Login Page',
  description: 'Generated by create next app',
};

export default function AuthPage({ children }) {
  return (
    <div className={styles.main}>
      <div className={styles.container}>
        <div className={styles.frame}>
          <div className={styles.leftBox}>
            <span className={styles.leftBoxTitle}>CanChu</span>
            {children}
          </div>
          <div className={styles.rightBox} />
        </div>
        <footer className={styles.footer}>
          關於我們 · 隱私權條款 · Cookie 條款 · © 2023 CanChu, Inc.
        </footer>
      </div>
    </div>
  );
}
