import '@/styles/global.css';
import 'github-markdown-css/github-markdown.css';
import UserProvider from './userContext';

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant-TW">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
