export const metadata = {
  title: 'Post Detail',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return <> {children}</>;
}
